name: Project build and test
on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create empty .env file
        run: touch .env
      - name: Run tests in Dev Container
        id: devcontainer-test
        uses: devcontainers/ci@v0.3
        continue-on-error: true
        with:
          push: never
          env: |
            WOKWI_CLI_TOKEN=${{ secrets.WOKWI_CLI_TOKEN }}
          runCmd: |
            idf.py -C blinky build
            robot --outputdir tmp/ tests/wokwi_serial.robot
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware-binaries
          path: |
            blinky/build/blinky.bin
            blinky/build/blinky.elf
            blinky/build/bootloader/bootloader.bin
            blinky/build/partition_table/partition-table.bin
            blinky/build/flasher_args.json
      - name: Upload Robot Framework results
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: tmp/
      - name: Check test outcome
        if: steps.devcontainer-test.outcome == 'failure'
        run: exit 1